import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
padding = {x=10, y = 10}
opacity = 0.8
blur = true

[font]
normal = { family = "Fira Code" }
bold = { family = "Fira Code" }
italic = { family = "Fira Code" }
bold_italic = { family = "Fira Code" }
size = 12


