vim.o.hlsearch = false
vim.o.incsearch = true
vim.o.number = true
vim.wo.relativenumber = true
vim.o.mouse = 'a'
vim.o.undofile = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.updatetime = 250
vim.wo.signcolumn = 'yes'
vim.o.termguicolors = true
vim.o.completeopt = 'menuone,noselect'
vim.o.clipboard = 'unnamed,unnamedplus'
vim.o.tabstop = 4
vim.o.expandtab = false
vim.o.shiftwidth = 0
vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { bg = 'none' })
